# Generated by Django 6.0.1 on 2026-02-13 13:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_member_serving_department_alter_member_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_date',
            field=models.DateField(default=core.models.get_today),
        ),
    ]
