# Generated by Django 6.0.1 on 2026-02-16 01:27

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_member_membership_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberTransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_reason', models.CharField(choices=[('JOB_TRANSFER', 'Job Transfer'), ('RELOCATION', 'Relocation'), ('FAMILY_REASONS', 'Family Reasons'), ('PERSONAL_CHOICE', 'Personal Choice'), ('OTHER', 'Other')], default='JOB_TRANSFER', max_length=20)),
                ('transfer_date', models.DateField(default=core.models.get_today)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_altar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members_transferred_from', to='core.organizationunit')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='core.member')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transfers', to=settings.AUTH_USER_MODEL)),
                ('to_altar', models.ForeignKey(blank=True, help_text='Destination altar (null if member is being deactivated)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members_transferred_to', to='core.organizationunit')),
            ],
            options={
                'db_table': 'member_transfer_history',
                'ordering': ['-transfer_date'],
                'indexes': [models.Index(fields=['member'], name='member_tran_member__abad4f_idx'), models.Index(fields=['transfer_date'], name='member_tran_transfe_e3c8bd_idx')],
            },
        ),
    ]
