# Generated by Django 6.0.1 on 2026-02-16 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_membertransferhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organizational_unit',
            field=models.ForeignKey(blank=True, help_text='The organizational unit this admin manages (region, sub-region, or altar)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_users', to='core.organizationunit'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organizational_unit'], name='users_organiz_3b2ba7_idx'),
        ),
    ]
