# Generated by Django 6.0.1 on 2026-02-02 14:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('visiting_from', models.CharField(blank=True, max_length=255, null=True)),
                ('first_visit_date', models.DateField(default=django.utils.timezone.now)),
                ('last_visit_date', models.DateField(default=django.utils.timezone.now)),
                ('visit_count', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'guests',
                'indexes': [models.Index(fields=['phone_number'], name='guests_phone_n_1b039a_idx'), models.Index(fields=['first_visit_date'], name='guests_first_v_a382ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('CONTINENT', 'Continent'), ('COUNTRY', 'Country'), ('REGION', 'Region'), ('SUB_REGION', 'Sub-Region'), ('ALTAR', 'Altar')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.organizationunit')),
            ],
            options={
                'db_table': 'organization_units',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('membership_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_altar', models.ForeignKey(limit_choices_to={'level': 'ALTAR'}, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='core.organizationunit')),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='AltarStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('member_attendance', models.IntegerField(default=0)),
                ('guest_count', models.IntegerField(default=0)),
                ('total_attendance', models.IntegerField(default=0)),
                ('avg_last_4_weeks', models.FloatField(blank=True, null=True)),
                ('avg_last_12_weeks', models.FloatField(blank=True, null=True)),
                ('guest_ratio', models.FloatField(blank=True, null=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_reason', models.TextField(blank=True, null=True)),
                ('reviewed_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('altar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizationunit')),
            ],
            options={
                'db_table': 'altar_statistics',
            },
        ),
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('service_type', models.CharField(choices=[('SUNDAY', 'Sunday Service'), ('MIDWEEK', 'Midweek Service'), ('SPECIAL', 'Special Event')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_schedules', to='core.organizationunit')),
            ],
            options={
                'db_table': 'service_schedules',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='core_users', related_query_name='core_user', to='auth.group', verbose_name='groups')),
                ('home_altar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_members', to='core.organizationunit')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='core_users', related_query_name='core_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'otp_codes',
            },
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='current_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_leading', to='core.user'),
        ),
        migrations.CreateModel(
            name='LeadershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadership_title', models.CharField(choices=[('PRESIDING_ARCHBISHOP', 'Presiding Archbishop'), ('NATIONAL_ARCHBISHOP', 'National Archbishop'), ('SENIOR_DEPUTY_ARCHBISHOP', 'Senior Deputy Archbishop'), ('BISHOP', 'Bishop'), ('DEPUTY_ARCHBISHOP', 'Deputy Archbishop'), ('OVERSEER', 'Overseer'), ('PASTOR', 'Pastor'), ('MEMBER', 'Member')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('TRANSFERRED', 'Transferred'), ('PROMOTED', 'Promoted'), ('RETIRED', 'Retired'), ('RESIGNED', 'Resigned'), ('DECEASED', 'Deceased'), ('REMOVED', 'Removed'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_history', to='core.organizationunit')),
                ('transferred_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_leaders', to='core.organizationunit')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leadership_assignments_made', to='core.user')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_positions', to='core.user')),
            ],
            options={
                'db_table': 'leadership_history',
            },
        ),
        migrations.CreateModel(
            name='DataEntryQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('attendance_records_created', models.IntegerField(default=0)),
                ('guests_registered', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'data_entry_quotas',
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_date', models.DateField()),
                ('service_type', models.CharField(choices=[('SUNDAY', 'Sunday Service'), ('MIDWEEK', 'Midweek Service'), ('SPECIAL', 'Special Event')], default='SUNDAY', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='core.guest')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='core.member')),
                ('altar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='altar_attendance_logs', to='core.organizationunit')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continent_attendance_logs', to='core.organizationunit')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_attendance_logs', to='core.organizationunit')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_attendance_logs', to='core.organizationunit')),
                ('sub_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_region_attendance_logs', to='core.organizationunit')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to='core.user')),
            ],
            options={
                'db_table': 'attendance_logs',
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['phone_number'], name='members_phone_n_e3a435_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['home_altar'], name='members_home_al_2e68ca_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['is_active'], name='members_is_acti_246c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['home_altar', 'is_active'], name='members_home_al_0a5b64_idx'),
        ),
        migrations.AddIndex(
            model_name='altarstatistics',
            index=models.Index(fields=['altar', 'date'], name='altar_stati_altar_i_b5ce8a_idx'),
        ),
        migrations.AddIndex(
            model_name='altarstatistics',
            index=models.Index(fields=['is_anomaly', 'reviewed_by_admin'], name='altar_stati_is_anom_551cdb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='altarstatistics',
            unique_together={('altar', 'date')},
        ),
        migrations.AddIndex(
            model_name='serviceschedule',
            index=models.Index(fields=['organization_unit', 'day_of_week'], name='service_sch_organiz_fcb418_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceschedule',
            index=models.Index(fields=['is_active'], name='service_sch_is_acti_1ebc52_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='users_phone_n_a3b1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['home_altar'], name='users_home_al_8b05d6_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['user', 'purpose'], name='otp_codes_user_id_93a783_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['code'], name='otp_codes_code_42d221_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['level'], name='organizatio_level_456465_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['parent'], name='organizatio_parent__5e7ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['level', 'parent'], name='organizatio_level_3d9f89_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_a90124_idx'),
        ),
        migrations.AddIndex(
            model_name='leadershiphistory',
            index=models.Index(fields=['organization_unit', 'end_date'], name='leadership__organiz_b244a2_idx'),
        ),
        migrations.AddIndex(
            model_name='leadershiphistory',
            index=models.Index(fields=['leader'], name='leadership__leader__ab12a0_idx'),
        ),
        migrations.AddIndex(
            model_name='leadershiphistory',
            index=models.Index(fields=['start_date'], name='leadership__start_d_cfd490_idx'),
        ),
        migrations.AddIndex(
            model_name='leadershiphistory',
            index=models.Index(fields=['end_date'], name='leadership__end_dat_9f9e60_idx'),
        ),
        migrations.AddIndex(
            model_name='dataentryquota',
            index=models.Index(fields=['user', 'date'], name='data_entry__user_id_8d1315_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dataentryquota',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['service_date', 'country'], name='attendance__service_789929_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['service_date', 'continent'], name='attendance__service_50e3c3_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['altar', 'service_date'], name='attendance__altar_i_5999b3_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['sub_region', 'service_date'], name='attendance__sub_reg_b5f03f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['region', 'service_date'], name='attendance__region__80764b_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancelog',
            constraint=models.UniqueConstraint(condition=models.Q(('member__isnull', False)), fields=('member', 'service_date'), name='unique_member_service_date'),
        ),
    ]
