# Generated by Django 5.1.15 on 2026-02-18 14:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='core_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='core_users', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Altar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_count', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('pastor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pastoring_altars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'altars',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='home_altar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_members', to='core.altar'),
        ),
        migrations.CreateModel(
            name='OrganizationNode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(db_index=True, help_text='Unique identifier (e.g., CENTRAL, NYERI, ALTAR_001)', max_length=50, unique=True)),
                ('path', models.CharField(db_index=True, help_text='Materialized path (e.g., /GLOBAL/AFRICA/KENYA/CENTRAL/)', max_length=1000, unique=True)),
                ('depth', models.IntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_altars', models.IntegerField(default=0)),
                ('total_members', models.IntegerField(default=0)),
                ('current_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_nodes', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.organizationnode')),
            ],
            options={
                'db_table': 'organization_nodes',
                'ordering': ['path'],
            },
        ),
        migrations.AddField(
            model_name='altar',
            name='parent_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='altars', to='core.organizationnode'),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_scope',
            field=models.ForeignKey(blank=True, help_text='The organizational node this user can manage (e.g., Central Region, Nyeri Sub-Region)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admins', to='core.organizationnode'),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('membership_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_altar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='core.altar')),
            ],
            options={
                'db_table': 'members',
                'indexes': [models.Index(fields=['home_altar', 'is_active'], name='members_home_al_0a5b64_idx'), models.Index(fields=['full_name'], name='members_full_na_398ca2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='organizationnode',
            index=models.Index(fields=['parent', 'is_active'], name='organizatio_parent__32a7b9_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationnode',
            index=models.Index(fields=['depth', 'is_active'], name='organizatio_depth_eb6ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationnode',
            index=models.Index(fields=['path'], name='organizatio_path_2a8b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationnode',
            index=django.contrib.postgres.indexes.GinIndex(fields=['path'], name='path_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='organizationnode',
            constraint=models.CheckConstraint(condition=models.Q(('depth__gte', 0)), name='depth_non_negative'),
        ),
        migrations.AddIndex(
            model_name='altar',
            index=models.Index(fields=['parent_node', 'is_active'], name='altars_parent__26fede_idx'),
        ),
        migrations.AddIndex(
            model_name='altar',
            index=models.Index(fields=['code'], name='altars_code_d52ee9_idx'),
        ),
        migrations.AddIndex(
            model_name='altar',
            index=models.Index(fields=['city'], name='altars_city_5c56f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['admin_scope', 'is_active'], name='users_admin_s_218b15_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['home_altar'], name='users_home_al_8b05d6_idx'),
        ),
    ]
