# Generated by Django 5.1.15 on 2026-02-23 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('visiting_from', models.CharField(blank=True, max_length=255)),
                ('first_visit_date', models.DateField()),
                ('last_visit_date', models.DateField()),
                ('visit_count', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visited_altar', models.ForeignKey(blank=True, db_column='visited_altar_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='core.altar')),
            ],
            options={
                'db_table': 'guests',
                'ordering': ['-last_visit_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_date', models.DateField(db_index=True)),
                ('service_type', models.CharField(choices=[('sunday_service', 'Sunday Service'), ('midweek_service', 'Midweek Service'), ('special_service', 'Special Service'), ('prayer_meeting', 'Prayer Meeting'), ('other', 'Other')], default='sunday_service', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('altar', models.ForeignKey(db_column='altar_id', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_logs', to='core.altar')),
                ('continent', models.ForeignKey(blank=True, db_column='continent_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='continent_attendance', to='core.organizationnode')),
                ('country', models.ForeignKey(blank=True, db_column='country_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_attendance', to='core.organizationnode')),
                ('member', models.ForeignKey(blank=True, db_column='member_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='core.member')),
                ('recorded_by', models.ForeignKey(db_column='recorded_by_id', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_recorded', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, db_column='region_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='region_attendance', to='core.organizationnode')),
                ('sub_region', models.ForeignKey(blank=True, db_column='sub_region_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_region_attendance', to='core.organizationnode')),
                ('guest', models.ForeignKey(blank=True, db_column='guest_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='core.guest')),
            ],
            options={
                'db_table': 'attendance_logs',
                'ordering': ['-service_date', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MemberTransferHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transfer_reason', models.CharField(choices=[('job_transfer', 'Job Transfer'), ('relocation', 'Relocation'), ('family_reasons', 'Family Reasons'), ('personal_choice', 'Personal Choice'), ('offboarding', 'Offboarding/Leaving'), ('other', 'Other')], db_column='transfer_reason', default='other', max_length=50)),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_altar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='core.altar')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='core.member')),
                ('processed_by', models.ForeignKey(blank=True, db_column='processed_by_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_processed', to=settings.AUTH_USER_MODEL)),
                ('to_altar', models.ForeignKey(blank=True, help_text='Null if member is being offboarded/deactivated', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='core.altar')),
            ],
            options={
                'verbose_name_plural': 'Member transfer histories',
                'db_table': 'member_transfer_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['visited_altar', 'last_visit_date'], name='guests_visited_4c5dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['full_name'], name='guests_full_na_681ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['service_date', 'altar'], name='attendance__service_c1dcbc_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['member', 'service_date'], name='attendance__member__1ab132_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['guest', 'service_date'], name='attendance__guest_i_6faeaa_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancelog',
            constraint=models.CheckConstraint(condition=models.Q(('member__isnull', False), ('guest__isnull', False), _connector='OR'), name='attendance_must_have_member_or_guest'),
        ),
        migrations.AddIndex(
            model_name='membertransferhistory',
            index=models.Index(fields=['member', 'created_at'], name='member_tran_member__d1cd43_idx'),
        ),
        migrations.AddIndex(
            model_name='membertransferhistory',
            index=models.Index(fields=['from_altar', 'created_at'], name='member_tran_from_al_b93b44_idx'),
        ),
        migrations.AddIndex(
            model_name='membertransferhistory',
            index=models.Index(fields=['to_altar', 'created_at'], name='member_tran_to_alta_29031a_idx'),
        ),
    ]
