# Generated by Django 6.0.1 on 2026-02-12 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth for age calculation', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='home_altar',
            field=models.ForeignKey(help_text='Department/Altar the member belongs to', limit_choices_to={'level': 'ALTAR'}, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='core.organizationunit'),
        ),
    ]
