# Generated by Django 6.0.1 on 2026-02-13 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_member_date_of_birth_alter_member_home_altar'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='serving_department',
            field=models.CharField(blank=True, help_text='Department where the member serves', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='full_name',
            field=models.CharField(help_text='Full name of the member', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], help_text='Gender of the member', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='home_altar',
            field=models.ForeignKey(help_text='Home altar the member belongs to', limit_choices_to={'level': 'ALTAR'}, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='core.organizationunit'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(help_text='Contact phone number', max_length=20, unique=True),
        ),
    ]
