# Generated by Django 5.1.15 on 2026-02-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enable_pg_trgm_extension'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organizationnode',
            name='path_gin_idx',
        ),
    ]
