# Generated by Django 5.1.15 on 2026-02-23 08:03

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_gin_trigram_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organizationnode',
            index=django.contrib.postgres.indexes.GinIndex(fields=['path'], name='path_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
